= Watchman

== Overview

Watchman is a lightweight logging service designed for personal projects and small teams. 
It offers a simpler alternative to complex open-source solutions like ELK stack, Prometheus, Grafana, etc. 
and aims to be easy to use and consume as little resources as possible.

I am writing Watchman to meet my own needs, and it is currently under development. I plan on releasing a relatively stable version soon.


== Current limitations:

* Incomplete client (no authentication)
* Missing log file rotation and log expiration

== System Requirements

Watchman has a small footprint and should run on most systems, but here are suggested requirements:

* 256 MB Memory 
* 1 vCPU
* 500 MB Free Disk Space
* Any GNU/Linux distribution with systemd
* Go lang 1.22 or higher
* sqlite3 3.46.0 or higher

> Above requirements assume that you are only running watchman's server on the server and running frontend on a seperate server.

=== API Documentation

API Endpoints along with usage examples are documented in link:./API.adoc[API.adoc] file.

